### PR TITLE
Upgrade web form 0.4.0 to 0.5.1

### PR DESCRIPTION
**Pull request by knottx**
Upgrade web form 0.4.0 to 0.5.1
@zmtzawqlp

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
we need to keep more version to fit.  https://github.com/fluttercandies/extended_image_library/issues/62

**Comment by mitch2na** [comment]
The dependencies as they stand now do not fit with the most recent version of firebase_storage

```
Because extended_image_library >=4.0.0 <4.0.2 depends on web ^0.3.0 and no versions of extended_image_library match >4.0.2 <5.0.0, extended_image_library >=4.0.0 <4.0.2-∞ or >4.0.2 <5.0.0 requires web ^0.3.0.
And because extended_image 8.2.0 depends on extended_image_library ^4.0.1 and extended_image_library 4.0.2 depends on web ^0.4.0, extended_image 8.2.0 requires web ^0.3.0 or ^0.4.0.
And because firebase_storage >=11.6.10 depends on firebase_storage_web ^3.8.0 which depends on web ^0.5.1, extended_image 8.2.0 is incompatible with firebase_storage >=11.6.10.
```

**Comment by aggeloskoutanis** [comment]
I also ended up here cause I am unable to upgrade firebase package. Please, consider merging this.

**Comment by alextekartik** [comment]
`>=0.4.0 <0.6.0` should work for everyone (damned having upper limits...)

**Comment by AlexV525** [comment]
Fixed in c330c9f138be4409dc1b8cb8b74165e1b43bab9d.

**Pull request closed without merging**
