### PR TITLE
Don't use listSync to look for cached files

### PR DESCRIPTION
**Pull request by moffatman**
If you have a lot of files it will block the main thread. We can use list() and await for loop instead.

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
It's a breaking change for everyone. it's better to add another method with async.

**Comment by moffatman** [comment]
The function is already async, it's not breaking

**Comment by zmtzawqlp** [comment]
> The function is already async, it's not breaking

so  if await this method, does it block the ui thread? 

there is a case that we should await to clear all cached files then do next. is it breaking the behavior？

**Comment by moffatman** [comment]
I noticed this problem in the current version, I await to getCachedImageFile, and my app freezes for 0.1 seconds since I have 20,000 cached images. When I switched it there is no lag. Anyone calling the function should already be using await properly.

**Comment by moffatman** [comment]
If you used clearDiskCachedImages without await, you would already see the wrong behavior, since it currently uses await for getTemporaryDirectory(). Current behavior is not to block until files are deleted, the blocking will happen a little while after the Future is returned, when the microtask is processed.

**Pull request merged**
